import { Injectable } from '@angular/core';

@Injectable()
export class LargeCapService {

  constructor() { }
  getStocks() {
        return [
            {
                "Lista":"Large Cap",
                "Namn":"Industrivärden C",
                "Borsvarde":82564,
                "Pe":5.12,
                "Peranking":0,
                "JekAktie":189.6,
                "JekRanking":0,
                "BraBilligRanking":0,
                "DirektAvkastning":2.7,
                "DaRanking":0,
                "RbbhsRanking":0
            },
            {
                "Lista":"Large Cap",
                "Namn":"Investor B",
                "Borsvarde":279807,
                "Pe":8.33,
                "PeRanking":0,
                "JekAktie":391.15,
                "JekRanking":0,
                "RbbRanking":0,
                "DirektAvkastning":3.01,
                "DaRanking":0,
                "RbbhsRanking":0
            },
            {
                "Lista":"Large Cap",
                "Namn":"Fingerprint Cards B",
                "Borsvarde":15840,
                "Pe":7.72,
                "PeRanking":0,
                "JekAktie":6.88,
                "JekRanking":0,
                "RbbRanking":0,
                "DirektAvkastning":4.10,
                "DaRanking":0,
                "RbbhsRanking":0
            },
            {
                "Lista":"Large Cap",
                "Namn":"Trelleborg B",
                "Borsvarde":50907,
                "Pe":7.73,
                "PeRanking":0,
                "JekAktie":92.73,
                "JekRanking":0,
                "RbbRanking":0,
                "DirektAvkastning":2.26,
                "DaRanking":0,
                "RbbhsRanking":0
            },
            {
                "Lista":"Large Cap",
                "Namn":"Swedish Match",
                "Borsvarde":53944,
                "Pe":10.44,
                "PeRanking":0,
                "JekAktie":-7,
                "JekRanking":0,
                "RbbRanking":0,
                "DirektAvkastning":5.6,
                "DaRanking":0,
                "RbbhsRanking":0
            },
            {
                "Lista":"Large Cap",
                "Namn":"Betsson B",
                "Borsvarde":11725,
                "Pe":13.23,
                "PeRanking":0,
                "JekAktie":24,
                "JekRanking":0,
                "RbbRanking":0,
                "DirektAvkastning":5.87,
                "DaRanking":0,
                "RbbhsRanking":0
            },
            {
                "Lista":"Large Cap",
                "Namn":"Thule Group",
                "Borsvarde":14984,
                "Pe":21.93,
                "PeRanking":0,
                "JekAktie":37.88,
                "JekRanking":0,
                "RbbRanking":0,
                "DirektAvkastning":7.43,
                "DaRanking":0,
                "RbbhsRanking":0
            },
            {
                "Lista":"Large Cap",
                "Namn":"Com Hem Holding",
                "Borsvarde":18895,
                "Pe":60.26,
                "PeRanking":0,
                "JekAktie":29.88,
                "JekRanking":0,
                "RbbRanking":0,
                "DirektAvkastning":4,
                "DaRanking":0,
                "RbbhsRanking":0
            },
            {
                "Lista":"Large Cap",
                "Namn":"AstraZeneca",
                "Borsvarde":674393,
                "Pe":21.12,
                "PeRanking":0,
                "JekAktie":107.14,
                "JekRanking":0,
                "RbbRanking":0,
                "DirektAvkastning":4.57,
                "DaRanking":0,
                "RbbhsRanking":0
            },
            {
                "Lista":"Large Cap",
                "Namn":"Telia Company",
                "Borsvarde":157441,
                "Pe":42.42,
                "PeRanking":0,
                "JekAktie":2.16,
                "JekRanking":0,
                "RbbRanking":0,
                "DirektAvkastning":5.77,
                "DaRanking":0,
                "RbbhsRanking":0
            },
            {
                "Lista":"Large Cap",
                "Namn":"Hennes & Mauritz B",
                "Borsvarde":405327,
                "Pe":21.75,
                "PeRanking":0,
                "JekAktie":37,
                "JekRanking":0,
                "RbbRanking":0,
                "DirektAvkastning":3.98,
                "DaRanking":0,
                "RbbhsRanking":0
            },
            {
                "Lista":"Large Cap",
                "Namn":"Skanska B",
                "Borsvarde":89439,
                "Pe":15.26,
                "PeRanking":0,
                "JekAktie":65.13,
                "JekRanking":0,
                "RbbRanking":0,
                "DirektAvkastning":3.87,
                "DaRanking":0,
                "RbbhsRanking":0
            },
            {
                "Lista":"Large Cap",
                "Namn":"Stora Enso R",
                "Borsvarde":8417,
                "Pe":17.95,
                "PeRanking":0,
                "JekAktie":7.36,
                "JekRanking":0,
                "RbbRanking":0,
                "DirektAvkastning":3.51,
                "DaRanking":0,
                "RbbhsRanking":0
            },
            {
                "Lista":"Large Cap",
                "Namn":"Elektrolux B",
                "Borsvarde":75645,
                "Pe":15.61,
                "PeRanking":0,
                "JekAktie":57.32,
                "JekRanking":0,
                "RbbRanking":0,
                "DirektAvkastning":3.07,
                "DaRanking":0,
                "RbbhsRanking":0
            },
            {
                "Lista":"Large Cap",
                "Namn":"Autoliv SDB",
                "Borsvarde":97656,
                "Pe":16.24,
                "PeRanking":0,
                "JekAktie":379.94,
                "JekRanking":0,
                "RbbRanking":0,
                "DirektAvkastning":2.25,
                "DaRanking":0,
                "RbbhsRanking":0
            },
            {
                "Lista":"Large Cap",
                "Namn":"Volvo B",
                "Borsvarde":268017,
                "Pe":19.46,
                "PeRanking":0,
                "JekAktie":45.13,
                "JekRanking":0,
                "RbbRanking":0,
                "DirektAvkastning":2.58,
                "DaRanking":0,
                "RbbhsRanking":0
            },
            {
                "Lista":"Large Cap",
                "Namn":"Sandvik",
                "Borsvarde":159307,
                "Pe":23.16,
                "PeRanking":0,
                "JekAktie":31.25,
                "JekRanking":0,
                "RbbRanking":0,
                "DirektAvkastning":2.17,
                "DaRanking":0,
                "RbbhsRanking":0
            },
            {
                "Lista":"Large Cap",
                "Namn":"ABB td",
                "Borsvarde":446492,
                "Pe":25.07,
                "PeRanking":0,
                "JekAktie":53.01,
                "JekRanking":0,
                "RbbRanking":0,
                "DirektAvkastning":3.21,
                "DaRanking":0,
                "RbbhsRanking":0
            },
            {
                "Lista":"Large Cap",
                "Namn":"Assa Abloy B",
                "Borsvarde":194367,
                "Pe":29.17,
                "PeRanking":0,
                "JekAktie":42.44,
                "JekRanking":0,
                "RbbRanking":0,
                "DirektAvkastning":1.72,
                "DaRanking":0,
                "RbbhsRanking":0
            },
            {
                "Lista":"Large Cap",
                "Namn":"Atlas Copco B",
                "Borsvarde":360152,
                "Pe":30.86,
                "PeRanking":0,
                "JekAktie":43.19,
                "JekRanking":0,
                "RbbRanking":0,
                "DirektAvkastning":2.25,
                "DaRanking":0,
                "RbbhsRanking":0
            },
            {
                "Lista":"Large Cap",
                "Namn":"SCA B",
                "Borsvarde":200894,
                "Pe":35.87,
                "PeRanking":0,
                "JekAktie":103.73,
                "JekRanking":0,
                "RbbRanking":0,
                "DirektAvkastning":2.11,
                "DaRanking":0,
                "RbbhsRanking":0
            },
        ]
  }
}
